site_name: Numériques et Sciences Informatiques
site_url: https://infocornouaille.github.io/nsi-cornouaille/
repo_url: https://github.com/infocornouaille/nsi-cornouaille/
edit_uri: edit/main/docs/
site_description: Cours de NSI en classe de Première et Terminale du lycée de Cornouaille à Quimper
site_author: David Couronné
plugins:
  - git-revision-date
  - search
  - macros



theme:
  name: material
  custom_dir: overrides
  language: fr
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette: 
 
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode


markdown_extensions:
  - abbr
  - attr_list
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
  
extra:           
  blog:
    dir: blog
    author: David Couronné
    words_read_per_minute: 300
    list_length: 25
    extended_preview: true
  


# Page tree
nav:
  - Accueil: index.md
  - Première NSI:
    - Accueil: premiere/index.md
    - Les bases de Python:
      - Principes de base de Python: premiere/bases_de_python/principes.md
      - Stockage dans des variables: premiere/bases_de_python/variables.md
      - Les booléens: premiere/bases_de_python/booleens.md
      - Les fonctions: premiere/bases_de_python/fonctions.md
      - Les structures conditionnelles: premiere/bases_de_python/ifelse.md
    - Représentation des nombres:
      - Le binaire: premiere/representation/binaire.md
      - Codage des entiers: premiere/representation/codage_entiers.md
      - Codage de non entiers: premiere/representation/codage_non_entiers.md
    - Types construits:
      - Les listes: premiere/types_construits/listes.md
      - Les tuple: premiere/types_construits/tuple.md
      - Les dictionnaires: premiere/types_construits/dictionnaires.md
    - Algorithmique:
      - Introduction: premiere/algorithmique/introduction.md
      - Parcours séquentiels: premiere/algorithmique/parcours.md
  - Terminale NSI:
    - Introduction: terminales/index.md
    - Sujets pratiques:
      - Banque de sujets 2022: terminales/sujets_pratiques/BSN_2022.md 
      - Sujet 1: terminales/sujets_pratiques/sujet1.md    
      - Sujet 2: terminales/sujets_pratiques/sujet2.md  
      - Sujet 3: terminales/sujets_pratiques/sujet3.md 
      - Sujet 4: terminales/sujets_pratiques/sujet4.md  
      - Sujet 11: terminales/sujets_pratiques/sujet11.md
      - Sujet 23: terminales/sujets_pratiques/sujet23.md
  - Ressources:
    - Anaconda et Miniconda: ressources/conda.md
    - Visual Studio Code: ressources/vscode.md
    - Types en Python: ressources/types.md
  - Blog:
      - blog/index.md
      - 2021:
          - blog/2021/mac-securiser-cloud.md

